# Generated by Django 6.0.2 on 2026-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salestransaction_kitchen_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gt', 0)), name='chk_dish_selling_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', models.F('cost_price'))), name='chk_dish_margin_valid'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='chk_raw_material_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('cost_per_unit__gte', 0)), name='chk_raw_material_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='chk_raw_material_reorder_level_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='chk_saleitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='chk_saleitem_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='chk_saleitem_line_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('sub_total__gte', 0)), name='chk_txn_subtotal_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_txn_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gte', 0)), name='chk_txn_amount_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('change_returned__gte', 0)), name='chk_txn_change_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='chk_txn_discount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salestransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'cash'), _negated=True), ('amount_received__gte', models.F('total_amount')), _connector='OR'), name='chk_txn_cash_payment_received_sufficient'),
        ),
    ]
