# Generated by Django 6.0.2 on 2026-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dish_chk_dish_selling_price_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
