# Generated by Django 6.0.2 on 2026-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], default='dine_in', max_length=20),
        ),
    ]
