# Generated by Django 6.0.2 on 2026-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salestransaction_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='table_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
