# Generated by Django 6.0.2 on 2026-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_salestransaction_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
