# Generated by Django 6.0.2 on 2026-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_purchaseorderitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='sale_date',
            field=models.DateField(db_index=True),
        ),
    ]
