# Generated by Django 6.0.2 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dish_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('litre', 'litre'), ('ml', 'ml'), ('piece', 'piece'), ('dozen', 'dozen')], max_length=20),
        ),
    ]
