# Generated by Django 6.0.4 on 2026-08-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('litre', 'Litres'), ('ml', 'Millilitres'), ('piece', 'Pieces'), ('dozen', 'Dozens'), ('packet', 'Packets'), ('bag', 'Bags'), ('bunch', 'Bunches'), ('bottle', 'Bottles'), ('block', 'Blocks'), ('tin', 'Tins'), ('crate', 'Crates'), ('glass', 'Glasses')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('litre', 'Litres'), ('ml', 'Millilitres'), ('piece', 'Pieces'), ('dozen', 'Dozens'), ('packet', 'Packets'), ('bag', 'Bags'), ('bunch', 'Bunches'), ('bottle', 'Bottles'), ('block', 'Blocks'), ('tin', 'Tins'), ('crate', 'Crates'), ('glass', 'Glasses')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='units',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('litre', 'Litres'), ('ml', 'Millilitres'), ('piece', 'Pieces'), ('dozen', 'Dozens'), ('packet', 'Packets'), ('bag', 'Bags'), ('bunch', 'Bunches'), ('bottle', 'Bottles'), ('block', 'Blocks'), ('tin', 'Tins'), ('crate', 'Crates'), ('glass', 'Glasses')], max_length=20),
        ),
    ]
